services:
  cooking:
    build:
      context: .
      dockerfile: ./apps/cooking/Dockerfile
      target: development
    command: npm run start:dev cooking
    env_file:
      - ./apps/cooking/.env
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  user-interaction:
    build:
      context: .
      dockerfile: ./apps/user-interaction/Dockerfile
      target: development
    command: npm run start:dev user-interaction
    env_file:
      - ./apps/user-interaction/.env
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports: 
      - '5672:5672'

  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
 